project:
  type: website

website:
  title: "ISS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
        - text: Hands-on Exercises 1
          href: Hands-on_Ex1/Hands-on_Ex1.qmd
      - text: In-class Exercises
        menu: 
        - text: In-class Exercises 1
          href: In-class_Ex1/In-class_Ex1.qmd
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

