project:
  type: website

website:
  title: "ISS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
        - text: Hands-on Exercises 1
          href: Hands-on_Ex1/Hands-on_Ex1.qmd
        - text: Hands-on Exercises 2
          href: Hands-on_Ex2/Hands-on_Ex2.qmd
        - text: Hands-on Exercises 3
          href: Hands-on_Ex3/Hands-on_Ex3.qmd 
      - text: In-class Exercises
        menu: 
        - text: In-class Exercises 1
          href: In-class_Ex1/In-class_Ex1.qmd
        - text: In-class Exercises 2
          href: In-class_Ex2/In-class_Ex2.qmd
        
      - text: Take-home Exercises
        menu: 
        - text: Take-home Exercises 1
          href: Take-home_Ex1/Take-home_Ex1.qmd
      
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

