<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.189">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Le Thanh Thao">

<title>ISS624 - Take-home Exercise 1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">ISS624</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false">Hands-on Exercises</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercises">    
        <li>
    <a class="dropdown-item" href="../Hands-on_Ex1/Hands-on_Ex1.html">
 <span class="dropdown-text">Hands-on Exercises 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../Hands-on_Ex2/Hands-on_Ex2.html">
 <span class="dropdown-text">Hands-on Exercises 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../Hands-on_Ex3/Hands-on_Ex3.html">
 <span class="dropdown-text">Hands-on Exercises 3</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false">In-class Exercises</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercises">    
        <li>
    <a class="dropdown-item" href="../In-class_Ex1/In-class_Ex1.html">
 <span class="dropdown-text">In-class Exercises 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../In-class_Ex2/In-class_Ex2.html">
 <span class="dropdown-text">In-class Exercises 2</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false">Take-home Exercises</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercises">    
        <li>
    <a class="dropdown-item" href="../Take-home_Ex1/Take-home_Ex1.html">
 <span class="dropdown-text">Take-home Exercises 1</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html">Home</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html">About</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#data-set" id="toc-data-set" class="nav-link" data-scroll-target="#data-set">Data Set</a>
  <ul class="collapse">
  <li><a href="#aspatial-data" id="toc-aspatial-data" class="nav-link" data-scroll-target="#aspatial-data">Aspatial Data</a></li>
  <li><a href="#geospatial-data" id="toc-geospatial-data" class="nav-link" data-scroll-target="#geospatial-data">Geospatial data</a></li>
  </ul></li>
  <li><a href="#getting-started" id="toc-getting-started" class="nav-link" data-scroll-target="#getting-started">Getting Started</a></li>
  <li><a href="#importing-data" id="toc-importing-data" class="nav-link" data-scroll-target="#importing-data">Importing data</a>
  <ul class="collapse">
  <li><a href="#importing-aspatial-data-in-csv-format" id="toc-importing-aspatial-data-in-csv-format" class="nav-link" data-scroll-target="#importing-aspatial-data-in-csv-format">Importing aspatial data in csv format</a></li>
  <li><a href="#creating-a-simple-data-feature-data-frame-from-an-aspatial-data-frame" id="toc-creating-a-simple-data-feature-data-frame-from-an-aspatial-data-frame" class="nav-link" data-scroll-target="#creating-a-simple-data-feature-data-frame-from-an-aspatial-data-frame">Creating a simple data feature data frame from an aspatial data frame</a></li>
  <li><a href="#importing-polygon-feature-data-in-shapefile-format" id="toc-importing-polygon-feature-data-in-shapefile-format" class="nav-link" data-scroll-target="#importing-polygon-feature-data-in-shapefile-format">Importing polygon feature data in shapefile format</a></li>
  </ul></li>
  <li><a href="#exploratory-data-analysis-eda" id="toc-exploratory-data-analysis-eda" class="nav-link" data-scroll-target="#exploratory-data-analysis-eda">Exploratory Data Analysis (EDA)</a></li>
  <li><a href="#geoprocessing-with-sf-package" id="toc-geoprocessing-with-sf-package" class="nav-link" data-scroll-target="#geoprocessing-with-sf-package">Geoprocessing with sf package</a>
  <ul class="collapse">
  <li><a href="#extracting-functional-water-points" id="toc-extracting-functional-water-points" class="nav-link" data-scroll-target="#extracting-functional-water-points">Extracting functional water points</a></li>
  <li><a href="#plotting-frequency-table-of-functional-water-points" id="toc-plotting-frequency-table-of-functional-water-points" class="nav-link" data-scroll-target="#plotting-frequency-table-of-functional-water-points">Plotting frequency table of functional water points</a></li>
  <li><a href="#extracting-non-functional-water-points" id="toc-extracting-non-functional-water-points" class="nav-link" data-scroll-target="#extracting-non-functional-water-points">Extracting non-functional water points</a></li>
  <li><a href="#plotting-frequency-table-of-non-functional-water-points" id="toc-plotting-frequency-table-of-non-functional-water-points" class="nav-link" data-scroll-target="#plotting-frequency-table-of-non-functional-water-points">Plotting frequency table of non-functional water points</a></li>
  <li><a href="#extracting-unknown-water-points" id="toc-extracting-unknown-water-points" class="nav-link" data-scroll-target="#extracting-unknown-water-points">Extracting unknown water points</a></li>
  <li><a href="#performing-point-in-polygon-count" id="toc-performing-point-in-polygon-count" class="nav-link" data-scroll-target="#performing-point-in-polygon-count">Performing Point-in-Polygon Count</a></li>
  </ul></li>
  <li><a href="#calculating-the-proportion-of-number-of-functional-non-functional-and-unknown-water-points-to-the-total-number-of-water-points-for-each-area-unit" id="toc-calculating-the-proportion-of-number-of-functional-non-functional-and-unknown-water-points-to-the-total-number-of-water-points-for-each-area-unit" class="nav-link" data-scroll-target="#calculating-the-proportion-of-number-of-functional-non-functional-and-unknown-water-points-to-the-total-number-of-water-points-for-each-area-unit">Calculating the proportion of number of functional, non-functional and unknown water points to the total number of water points for each area unit</a></li>
  <li><a href="#visualizing-the-spatial-distribution-of-number-of-water-points" id="toc-visualizing-the-spatial-distribution-of-number-of-water-points" class="nav-link" data-scroll-target="#visualizing-the-spatial-distribution-of-number-of-water-points">Visualizing the spatial distribution of number of water points</a></li>
  <li><a href="#visualizing-the-spatial-distribution-of-water-point-rates" id="toc-visualizing-the-spatial-distribution-of-water-point-rates" class="nav-link" data-scroll-target="#visualizing-the-spatial-distribution-of-water-point-rates">Visualizing the spatial distribution of water point rates</a></li>
  <li><a href="#determining-appropriate-weighting-scheme-to-calculate-spatial-weight-matrix" id="toc-determining-appropriate-weighting-scheme-to-calculate-spatial-weight-matrix" class="nav-link" data-scroll-target="#determining-appropriate-weighting-scheme-to-calculate-spatial-weight-matrix">Determining appropriate weighting scheme to calculate spatial weight matrix</a>
  <ul class="collapse">
  <li><a href="#computing-contiguity-spatial-weights" id="toc-computing-contiguity-spatial-weights" class="nav-link" data-scroll-target="#computing-contiguity-spatial-weights">Computing Contiguity Spatial Weights</a></li>
  <li><a href="#distance-based-weight-matrix" id="toc-distance-based-weight-matrix" class="nav-link" data-scroll-target="#distance-based-weight-matrix">Distance based Weight Matrix</a></li>
  </ul></li>
  <li><a href="#global-spatial-autocorrelation-morans-i" id="toc-global-spatial-autocorrelation-morans-i" class="nav-link" data-scroll-target="#global-spatial-autocorrelation-morans-i">Global Spatial Autocorrelation: Moran’s I</a>
  <ul class="collapse">
  <li><a href="#morans-i-test" id="toc-morans-i-test" class="nav-link" data-scroll-target="#morans-i-test">Moran’s I test</a></li>
  <li><a href="#gearys-c" id="toc-gearys-c" class="nav-link" data-scroll-target="#gearys-c">Geary’s c</a></li>
  </ul></li>
  <li><a href="#cluster-and-outlier-analysis" id="toc-cluster-and-outlier-analysis" class="nav-link" data-scroll-target="#cluster-and-outlier-analysis">Cluster and Outlier Analysis</a>
  <ul class="collapse">
  <li><a href="#computing-local-morans-i" id="toc-computing-local-morans-i" class="nav-link" data-scroll-target="#computing-local-morans-i">Computing local Moran’s I</a></li>
  <li><a href="#mapping-the-local-morans-i-statistics" id="toc-mapping-the-local-morans-i-statistics" class="nav-link" data-scroll-target="#mapping-the-local-morans-i-statistics">Mapping the local Moran’s I statistics</a></li>
  <li><a href="#mapping-local-morans-i-statistics" id="toc-mapping-local-morans-i-statistics" class="nav-link" data-scroll-target="#mapping-local-morans-i-statistics">Mapping local Moran’s I statistics</a></li>
  <li><a href="#mapping-local-morans-i-p-values" id="toc-mapping-local-morans-i-p-values" class="nav-link" data-scroll-target="#mapping-local-morans-i-p-values">Mapping local Moran’s I p-values</a></li>
  <li><a href="#mapping-both-local-morans-i-statistics-and-p-values" id="toc-mapping-both-local-morans-i-statistics-and-p-values" class="nav-link" data-scroll-target="#mapping-both-local-morans-i-statistics-and-p-values">Mapping both local Moran’s I statistics and p-values</a></li>
  <li><a href="#interpretation-of-local-morans-statistics" id="toc-interpretation-of-local-morans-statistics" class="nav-link" data-scroll-target="#interpretation-of-local-morans-statistics">Interpretation of Local Moran’s statistics</a></li>
  </ul></li>
  <li><a href="#creating-a-lisa-cluster-map" id="toc-creating-a-lisa-cluster-map" class="nav-link" data-scroll-target="#creating-a-lisa-cluster-map">Creating a LISA Cluster Map</a>
  <ul class="collapse">
  <li><a href="#plotting-moran-scatterplot" id="toc-plotting-moran-scatterplot" class="nav-link" data-scroll-target="#plotting-moran-scatterplot">Plotting Moran scatterplot</a></li>
  <li><a href="#plotting-moran-scatterplot-with-standardized-variable" id="toc-plotting-moran-scatterplot-with-standardized-variable" class="nav-link" data-scroll-target="#plotting-moran-scatterplot-with-standardized-variable">Plotting Moran scatterplot with standardized variable</a></li>
  <li><a href="#preparing-lisa-map-classes" id="toc-preparing-lisa-map-classes" class="nav-link" data-scroll-target="#preparing-lisa-map-classes">Preparing LISA map classes</a></li>
  <li><a href="#plotting-lisa-map" id="toc-plotting-lisa-map" class="nav-link" data-scroll-target="#plotting-lisa-map">Plotting LISA Map</a></li>
  </ul></li>
  <li><a href="#hot-spot-and-cold-spot-analysis" id="toc-hot-spot-and-cold-spot-analysis" class="nav-link" data-scroll-target="#hot-spot-and-cold-spot-analysis">Hot Spot and Cold Spot Analysis</a>
  <ul class="collapse">
  <li><a href="#gi-statistics-using-adaptive-distance" id="toc-gi-statistics-using-adaptive-distance" class="nav-link" data-scroll-target="#gi-statistics-using-adaptive-distance">Gi statistics using adaptive distance</a></li>
  <li><a href="#mapping-gi-values-with-adaptive-distance-weights" id="toc-mapping-gi-values-with-adaptive-distance-weights" class="nav-link" data-scroll-target="#mapping-gi-values-with-adaptive-distance-weights">Mapping Gi values with adaptive distance weights</a></li>
  </ul></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">Limitations</a></li>
  <li><a href="#reference" id="toc-reference" class="nav-link" data-scroll-target="#reference">Reference</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take-home Exercise 1</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Le Thanh Thao </p>
          </div>
  </div>
    
    
  </div>
  

</header>

<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>In this take home exercise, we will apply appropriate global and local measures of spatial association techniques to reveal the spatial patterns of Non-Functional water points in Nigeria.</p>
</section>
<section id="data-set" class="level2">
<h2 class="anchored" data-anchor-id="data-set">Data Set</h2>
<section id="aspatial-data" class="level3">
<h3 class="anchored" data-anchor-id="aspatial-data">Aspatial Data</h3>
<p>WPdx+ dataset of Nigeria in csv format was downloaded WPdx (Water Point Data Exchange) Global Data Repositories. The dataset contains water points related data from rural areas at the water point or small water scheme level. The dataset will be re-named as geo_export.csv saved under data/aspatial folder.</p>
</section>
<section id="geospatial-data" class="level3">
<h3 class="anchored" data-anchor-id="geospatial-data">Geospatial data</h3>
<p>Nigeria Level-2 Administrative Boundary (also known as Local Government Area) polygon features GIS data was downloaded from geoBoundaries portal. The file names were “geoBoundaries-NGA-ADM2” with different file formats and saved under data/geospatial folder.</p>
</section>
</section>
<section id="getting-started" class="level2">
<h2 class="anchored" data-anchor-id="getting-started">Getting Started</h2>
<p>First, we will install and download relevant packages for this exercises by using p_load() under pacman packages.</p>
<ul>
<li><p>sf for importing, managing and processing geospatial data, and</p></li>
<li><p>tidyverse for performing data science tasks such as importing, wrangling and visualizing data, and</p></li>
<li><p>spdep for computing spatial weights, global and local spatial autocorrelation statistics, and</p></li>
<li><p>tmap for preparing cartographic quality choropleth map</p></li>
<li><p>funModelling for exploratory data analysis, particularly for the DEA analysis in the later part</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf,tidyverse,spdep,tmap,funModeling)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="importing-data" class="level2">
<h2 class="anchored" data-anchor-id="importing-data">Importing data</h2>
<section id="importing-aspatial-data-in-csv-format" class="level3">
<h3 class="anchored" data-anchor-id="importing-aspatial-data-in-csv-format">Importing aspatial data in csv format</h3>
<p>Since geo_export data set was downloaded in csv format, read_csv() function is used to read to import geo_export.csv</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>wp<span class="ot">&lt;-</span><span class="fu">read_csv</span>(<span class="st">"data/aspatial/geo_export.csv"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(wp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>From the above message, there are in total 95008 observations with 70 columns.</p>
<p>The below code chunks provides the list for wp object:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">list</span>(wp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="creating-a-simple-data-feature-data-frame-from-an-aspatial-data-frame" class="level3">
<h3 class="anchored" data-anchor-id="creating-a-simple-data-feature-data-frame-from-an-aspatial-data-frame">Creating a simple data feature data frame from an aspatial data frame</h3>
<p>The below code chunks convert wp data frame into a simple feature data frame (sf object) by using st_as_sf() function of sf packages:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>wp_sf<span class="ot">&lt;-</span><span class="fu">st_as_sf</span>(wp,<span class="at">coords=</span><span class="fu">c</span>(<span class="st">"#lon_deg"</span>,<span class="st">"#lat_deg"</span>),<span class="at">crs=</span><span class="dv">4326</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Things to learn from the above code chunks:</p>
<ul>
<li><p>coords argument requires us to provide the column name of x-coordinates followed by the column name of y-coordinates.</p></li>
<li><p>crs argument requires us to provide the coordinate system in EPSG format. EPSG 4326 is the WGS84 Geographic Coordinates System.</p></li>
</ul>
<p>In order to learn more about the attributes of the newly created sf object, we use the following code chunks:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(wp_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can also view the coordinates system of wp_sf by using the below code chunks:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(wp_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We then save the extracted data which is (wp_sf) into an output file in rds data format. The output file is called wp_nga.rds and saved under geospatial sub-folder.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(wp_sf,<span class="st">"data/geospatial/wp_nga.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="importing-polygon-feature-data-in-shapefile-format" class="level3">
<h3 class="anchored" data-anchor-id="importing-polygon-feature-data-in-shapefile-format">Importing polygon feature data in shapefile format</h3>
<p>In the below code chunks, we use st_read() function of sf package to import <code>geoBoundaries-NGA-ADM2</code> Shapefile into R as a polygon feature data frame. Note that there are 2 arguments used when the input geospatial data is in shapefile format, namely: dsn to define the data path and layer to provide the Shapefile name. Notice that we do not need to indicate file extension.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>nga<span class="ot">&lt;-</span><span class="fu">st_read</span>(<span class="at">dsn=</span><span class="st">"data/geospatial"</span>,<span class="at">layer=</span><span class="st">"geoBoundaries-NGA-ADM2"</span>,<span class="at">crs=</span><span class="dv">4326</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>From the above summary, we learn that the geometry type is Multipolygon. There are in total 774 features and 70 columns.</p>
<p>We can confirm the coordinates system again by using the <em>st_crs()</em> function of <strong>sf</strong> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(nga)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can use <em>st_geometry()</em> function of <strong>sf</strong> package to retrieve the basic information on the type of geometry, the geographic extent of the features, and the coordinates system of the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_geometry</span>(nga)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can plot only the geometry of Nigeria using the below code chunk:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">st_geometry</span>(nga))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>However, some of the values under the the column <code>#status_clean</code>,which we need to use in the analysis to identify the working condition of the water points, are NA. Therefore, additional step required to replace NA values to Unknown.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>wp_nga<span class="ot">&lt;-</span><span class="fu">read_rds</span>(<span class="st">"data/geospatial/wp_nga.rds"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">#status_clean</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">replace_na</span>(<span class="st">`</span><span class="at">#status_clean</span><span class="st">`</span>,<span class="st">"Unknown"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In the above code chunks, the newly created wp_nga.rds file was read and mutate() function of dplyr package was used to amend those NA values under column <code>#status_clean</code> to Unknown values.</p>
</section>
</section>
<section id="exploratory-data-analysis-eda" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis-eda">Exploratory Data Analysis (EDA)</h2>
<p>We then plot a frequency table based on the column <code>#status_clean</code> using the below code chunk:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(<span class="at">data=</span>wp_nga,<span class="at">input=</span><span class="st">"#status_clean"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>freq()</em> of <strong>funModelling</strong> package mentioned above is used to generate and format frequency tables from a variable or a table, with percentages and formatting options.</p>
<p>From the above frequency table, we can group those under “Functional”, “Functional but needs repair”,“Functional but not in use” and categorize them as “Functional Water Points”, while those under “Non-Functional”,“Non-Functional due to dry season”,“Abandoned/Decommissioned”,“Abandoned”,“Non functional due to dry season” are categorized as “Non-Functional Water Points”. Keep this in mind for the rest of the analysis.</p>
</section>
<section id="geoprocessing-with-sf-package" class="level2">
<h2 class="anchored" data-anchor-id="geoprocessing-with-sf-package">Geoprocessing with sf package</h2>
<p>In this section, we will perform a wide range of geoprocessing with one commonly used geogprocessing functions: point in polygon count.</p>
<p>However, we will need to extract relevant data about the number of water points first under different categories: functional, non-functional and unknown.</p>
<section id="extracting-functional-water-points" class="level3">
<h3 class="anchored" data-anchor-id="extracting-functional-water-points">Extracting functional water points</h3>
<p>In the code chunks below, <em>filter()</em> of <strong>dplyr</strong> package is used to select functional water points.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>wpt_functional <span class="ot">&lt;-</span>wp_nga <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="st">`</span><span class="at">#status_clean</span><span class="st">`</span> <span class="sc">%in%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>           <span class="fu">c</span>(<span class="st">"Functional"</span>,<span class="st">"Functional but needs repair"</span>,<span class="st">"Functional but not in use"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="plotting-frequency-table-of-functional-water-points" class="level3">
<h3 class="anchored" data-anchor-id="plotting-frequency-table-of-functional-water-points">Plotting frequency table of functional water points</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(<span class="at">data=</span>wpt_functional,<span class="at">input=</span><span class="st">"#status_clean"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="extracting-non-functional-water-points" class="level3">
<h3 class="anchored" data-anchor-id="extracting-non-functional-water-points">Extracting non-functional water points</h3>
<p>In the code chunks below, <em>filter()</em> of <strong>dplyr</strong> package is used to select non-functional water points.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>wpt_nonfunctional<span class="ot">&lt;-</span>wp_nga <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="st">`</span><span class="at">#status_clean</span><span class="st">`</span> <span class="sc">%in%</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">"Non-Functional"</span>,<span class="st">"Non-Functional due to dry season"</span>,<span class="st">"Abandoned/Decommissioned"</span>,<span class="st">"Abandoned"</span>,<span class="st">"Non functional due to dry season"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="plotting-frequency-table-of-non-functional-water-points" class="level3">
<h3 class="anchored" data-anchor-id="plotting-frequency-table-of-non-functional-water-points">Plotting frequency table of non-functional water points</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(<span class="at">data=</span>wpt_nonfunctional,<span class="at">input=</span><span class="st">"#status_clean"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="extracting-unknown-water-points" class="level3">
<h3 class="anchored" data-anchor-id="extracting-unknown-water-points">Extracting unknown water points</h3>
<p>In the code chunks below, <em>filter()</em> of <strong>dplyr</strong> package is used to select unknown water points.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>wpt_unknown<span class="ot">&lt;-</span>wp_nga<span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="st">`</span><span class="at">#status_clean</span><span class="st">`</span><span class="sc">==</span><span class="st">"Unknown"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="performing-point-in-polygon-count" class="level3">
<h3 class="anchored" data-anchor-id="performing-point-in-polygon-count">Performing Point-in-Polygon Count</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>nga_wp<span class="ot">&lt;-</span>nga <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">total wpt</span><span class="st">`</span><span class="ot">=</span><span class="fu">lengths</span>(<span class="fu">st_intersects</span>(nga,wp_nga)))<span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">wpt functional</span><span class="st">`</span><span class="ot">=</span><span class="fu">lengths</span>(<span class="fu">st_intersects</span>(nga,wpt_functional)))<span class="sc">%&gt;%</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">wpt nonfunctional</span><span class="st">`</span><span class="ot">=</span><span class="fu">lengths</span>(<span class="fu">st_intersects</span>(nga,wpt_nonfunctional)))<span class="sc">%&gt;%</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">wpt unknown</span><span class="st">`</span><span class="ot">=</span><span class="fu">lengths</span>(<span class="fu">st_intersects</span>(nga,wpt_unknown)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In the above code chunks, these are the below operations done:</p>
<ul>
<li><p>First, <em>st_intersects()</em> function helps identify the water points under these 4 categories (set in the previous part): total, functional, non-functional and unknown, respectively in each area unit.</p></li>
<li><p>Next, <em>lengths()</em> function of Base R helps calculate the number of water points for each category: total, functional, non-function and unknown that fall into each area unit.</p></li>
<li><p>Last, <em>mutate()</em> function helps create the new columns for the newly calculated values and name them as <code>total wpt</code> <code>wpt functional</code> <code>wpt nonfunctional</code> <code>wpt unknown</code>.</p></li>
</ul>
<p>We can check the summary statistics of the newly derived fields of <code>total wpt</code> <code>wpt functional</code> <code>wpt nonfunctional</code> <code>wpt unknown</code> using the below code chunks:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nga_wp<span class="sc">$</span><span class="st">`</span><span class="at">wpt functional</span><span class="st">`</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nga_wp<span class="sc">$</span><span class="st">`</span><span class="at">wpt nonfunctional</span><span class="st">`</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nga_wp<span class="sc">$</span><span class="st">`</span><span class="at">wpt unknown</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="calculating-the-proportion-of-number-of-functional-non-functional-and-unknown-water-points-to-the-total-number-of-water-points-for-each-area-unit" class="level2">
<h2 class="anchored" data-anchor-id="calculating-the-proportion-of-number-of-functional-non-functional-and-unknown-water-points-to-the-total-number-of-water-points-for-each-area-unit">Calculating the proportion of number of functional, non-functional and unknown water points to the total number of water points for each area unit</h2>
<p>The below code chunks compute the proportion of functional, non-functional and unknown water points to the total number of water points for each area unit. The code chunks also name the newly created fields as <code>pct functional</code>, <code>pct nonfunctional</code>, <code>pct unknown</code>. These fields will be very crucial in our analysis for the rest of the exercise.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>nga_wp<span class="ot">&lt;-</span>nga_wp<span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">pct functional</span><span class="st">`</span><span class="ot">=</span><span class="st">`</span><span class="at">wpt functional</span><span class="st">`</span><span class="sc">/</span><span class="st">`</span><span class="at">total wpt</span><span class="st">`</span>)<span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">pct nonfunctional</span><span class="st">`</span><span class="ot">=</span><span class="st">`</span><span class="at">wpt nonfunctional</span><span class="st">`</span><span class="sc">/</span><span class="st">`</span><span class="at">total wpt</span><span class="st">`</span>)<span class="sc">%&gt;%</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">pct unknown</span><span class="st">`</span><span class="ot">=</span><span class="st">`</span><span class="at">wpt unknown</span><span class="st">`</span><span class="sc">/</span><span class="st">`</span><span class="at">total wpt</span><span class="st">`</span>)<span class="sc">%&gt;%</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">6</span><span class="sc">:</span><span class="dv">13</span>)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>nga_wp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Do note that the above <em>select()</em> function selects the relevant fields to keep for further analysis. In this case, we keep ShapeName (column 1), shapeID (column 3), from total wpt column to geometry column (column 6 to 13).</p>
<p>We then use <em>write_rds()</em> function below to create a new data file with a much smaller size of 2.1MB.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(nga_wp,<span class="st">"data/geospatial/nga_wp.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="visualizing-the-spatial-distribution-of-number-of-water-points" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-the-spatial-distribution-of-number-of-water-points">Visualizing the spatial distribution of number of water points</h2>
<p>In the below code chunks, we graph a simple map of the spatial distribution of the number of functional, non-functional and unknown water point at LGA level.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>nga_wp<span class="ot">&lt;-</span><span class="fu">read_rds</span>(<span class="st">"data/geospatial/nga_wp.rds"</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>total<span class="ot">&lt;-</span><span class="fu">qtm</span>(nga_wp,<span class="st">"total wpt"</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>wp_functional<span class="ot">&lt;-</span><span class="fu">qtm</span>(nga_wp,<span class="st">"wpt functional"</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>wp_nonfunctional<span class="ot">&lt;-</span><span class="fu">qtm</span>(nga_wp,<span class="st">"wpt nonfunctional"</span>)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>wp_unknown<span class="ot">&lt;-</span><span class="fu">qtm</span>(nga_wp,<span class="st">"wpt unknown"</span>)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(total,wp_functional,wp_nonfunctional,wp_unknown,<span class="at">asp=</span><span class="dv">1</span>,<span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex1_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="1344"></p>
</div>
</div>
</section>
<section id="visualizing-the-spatial-distribution-of-water-point-rates" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-the-spatial-distribution-of-water-point-rates">Visualizing the spatial distribution of water point rates</h2>
<p>In the below code chunks, we graph a simple map of the spatial distribution of functional, non-functional and unknown water point rates at LGA level. However, our focus for this exercise will be more on the non-functional water point rate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>pct_functional<span class="ot">&lt;-</span><span class="fu">qtm</span>(nga_wp,<span class="st">"pct functional"</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>pct_nonfunctional<span class="ot">&lt;-</span><span class="fu">qtm</span>(nga_wp,<span class="st">"pct nonfunctional"</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>pct_unknown<span class="ot">&lt;-</span><span class="fu">qtm</span>(nga_wp,<span class="st">"pct unknown"</span>)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(pct_functional,pct_nonfunctional,pct_unknown,<span class="at">asp=</span><span class="dv">1</span>,<span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex1_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="1344"></p>
</div>
</div>
<p>Notice that there are “Missing values” in all three maps. It was due to NaN values under the corresponding volumes for <code>pct functional</code>, <code>pct nonfunctional</code>, <code>pct unknown</code> as some of the regions do not have any water points at all, thus dividing by 0. More details and further processing will be covered under Distance based weight matrix below.</p>
</section>
<section id="determining-appropriate-weighting-scheme-to-calculate-spatial-weight-matrix" class="level2">
<h2 class="anchored" data-anchor-id="determining-appropriate-weighting-scheme-to-calculate-spatial-weight-matrix">Determining appropriate weighting scheme to calculate spatial weight matrix</h2>
<p>Before computing global spatial autocorrelation statistics, we will need to construct a spatial weights matrix of the area under study. The spatial weights is used to define the neighborhood relationship between geographic units in the study area.</p>
<p>We will then test a few weighting schemes to find out the most appropriate approach for us to compute the spatial weight matrix. We will start with contiguity based approach and move on to distance based approach.</p>
<section id="computing-contiguity-spatial-weights" class="level3">
<h3 class="anchored" data-anchor-id="computing-contiguity-spatial-weights">Computing Contiguity Spatial Weights</h3>
<p>In the below code chunks, we use <em>poly2nb()</em> function of <strong>spdep</strong> package to compute contiguity based weight matrices for the study area. This function builds a neighbors list based on regions with contiguous boundaries. The Queen argument in the below code chunks, if TRUE, a single shared boundary meets the contiguity condition, if FALSE, more than one shared point is required; note that more one shared boundary point does not necessarily mean a shared boundary line.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>wm_q<span class="ot">&lt;-</span><span class="fu">poly2nb</span>(nga_wp,<span class="at">queen=</span><span class="cn">TRUE</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wm_q)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 774 
Number of nonzero links: 4440 
Percentage nonzero weights: 0.7411414 
Average number of links: 5.736434 
1 region with no links:
86
Link number distribution:

  0   1   2   3   4   5   6   7   8   9  10  11  12  14 
  1   2  14  57 125 182 140 122  72  41  12   4   1   1 
2 least connected regions:
138 560 with 1 link
1 most connected region:
508 with 14 links</code></pre>
</div>
</div>
<p>The above summary shows that there are 774 area units in Nigeria. The most connected area unit with ID 508 has 14 links while the least connected area units have 1 link. There is also an area unit without any link based on the contiguity based with ID 86.</p>
<p>We can find out the name of the most connected area unit that has links as well as the 14 links’ ID using the below code chunks:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>nga_wp<span class="sc">$</span>shapeName[<span class="dv">508</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Mokwa"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>wm_q[<span class="dv">508</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
 [1]  20 106 123 171 174 239 402 419 468 471 494 511 644 753</code></pre>
</div>
</div>
<p>In order to find out the name and some info about the “special” region that has no links, we use the below code chunks</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>nga_wp<span class="sc">$</span>shapeName[<span class="dv">86</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Bakassi"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>nga_wp[<span class="dv">86</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 1 feature and 9 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 8.553504 ymin: 4.798471 xmax: 8.589043 ymax: 4.816385
Geodetic CRS:  WGS 84
   shapeName                    shapeID total wpt wpt functional
86   Bakassi NGA-ADM2-72505758B25708171         0              0
   wpt nonfunctional wpt unknown pct functional pct nonfunctional pct unknown
86                 0           0            NaN               NaN         NaN
                         geometry
86 MULTIPOLYGON (((8.580903 4....</code></pre>
</div>
</div>
<p>This seems to be a very interesting observation. Bakassi is a peninsula on the Gulf of Guinea and is famous for being an oil-rich area. It has been a subject of territorial dispute between Cameroon and Nigeria for some years. Under the terms of a 2002 International Court of Justice ruling, the region was awarded to Cameroon. Interestingly, in this analysis, this region was considered part of Nigeria’s territory. This could be because most of the population on Bakassi Peninsula are Nigerians.</p>
<p>More reference about ICJ’s Ruling on Bakassi Territorial Dispute can be found here. <a href="https://www.loc.gov/item/global-legal-monitor/2013-08-23/cameroon-nigeria-bakassi-peninsula-transition-completed/" class="uri">https://www.loc.gov/item/global-legal-monitor/2013-08-23/cameroon-nigeria-bakassi-peninsula-transition-completed/</a></p>
<p>Controversy aside, since there is a region found with no neighbor, we now can consider using distance based weight matrix instead to ensure each region has some links at least.</p>
</section>
<section id="distance-based-weight-matrix" class="level3">
<h3 class="anchored" data-anchor-id="distance-based-weight-matrix">Distance based Weight Matrix</h3>
<section id="transforming-from-geographic-coordinates-system-epsg-3426-to-projected-coordinates-system-epsg-26391" class="level4">
<h4 class="anchored" data-anchor-id="transforming-from-geographic-coordinates-system-epsg-3426-to-projected-coordinates-system-epsg-26391">Transforming from geographic coordinates system EPSG 3426 to projected coordinates system EPSG 26391</h4>
<p>Since we want to calculate distance, it is advisable to transform the current WGS84 geographic coordinates system to EPSG 26391 Projected Coordinates System for Nigeria using the below code chunks:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>nga_wp26391<span class="ot">&lt;-</span><span class="fu">read_rds</span>(<span class="st">"data/geospatial/nga_wp.rds"</span>)<span class="sc">%&gt;%</span> </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">pct functional</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">replace_na</span>(<span class="st">`</span><span class="at">pct functional</span><span class="st">`</span>,<span class="dv">0</span>))<span class="sc">%&gt;%</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">pct nonfunctional</span><span class="st">`</span><span class="ot">=</span><span class="fu">replace_na</span>(<span class="st">`</span><span class="at">pct nonfunctional</span><span class="st">`</span>,<span class="dv">0</span>))<span class="sc">%&gt;%</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">pct unknown</span><span class="st">`</span><span class="ot">=</span><span class="fu">replace_na</span>(<span class="st">`</span><span class="at">pct unknown</span><span class="st">`</span>,<span class="dv">0</span>))<span class="sc">%&gt;%</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs=</span><span class="dv">26391</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Besides transforming the coordinates system, the above code chunks also replace NaN values under <code>pct functional</code>, <code>pct nonfunctional</code> and <code>pct unknown</code> to 0 as the total water points for some areas were indeed 0 (i.e There were no water points at all for some regions. Therefore, when calculating rate/proportion, division by 0 would end up with NaN values.)</p>
<p>We can use function <em>st_crs()</em> to confirm if the projected coordinates system is indeed EPSG 26391.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(nga_wp26391)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: EPSG:26391 
  wkt:
PROJCRS["Minna / Nigeria West Belt",
    BASEGEOGCRS["Minna",
        DATUM["Minna",
            ELLIPSOID["Clarke 1880 (RGS)",6378249.145,293.465,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4263]],
    CONVERSION["Nigeria West Belt",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",4,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",4.5,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.99975,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",230738.26,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Engineering survey, topographic mapping."],
        AREA["Nigeria - onshore west of 6°30'E, onshore and offshore shelf."],
        BBOX[3.57,2.69,13.9,6.5]],
    ID["EPSG",26391]]</code></pre>
</div>
</div>
</section>
<section id="deriving-the-centroids" class="level4">
<h4 class="anchored" data-anchor-id="deriving-the-centroids">Deriving the centroids</h4>
<p>Since we are working with polygon for this exercise, we will need to get polygon centroids in order to make our connectivity graph. We will need to calculate the centroids using the sf package before moving to plot relevant maps. To do this, we will need to use mapping function. The mapping function applies a given function to each element of a vector and returns a vector of the same length. The input vector will be the geometry column of us.bound. The function will be <em>st_centroid()</em>. We will be using map_dbl variation of map from the purrr package.</p>
<p>To get the longitude values, we map the <em>st_centroid()</em> function over the geometry column of us.bound and access ONLY the longitude values through double bracket operation [[1]]</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>longitude<span class="ot">&lt;-</span><span class="fu">map_dbl</span>(nga_wp26391<span class="sc">$</span>geometry,<span class="sc">~</span><span class="fu">st_centroid</span>(.x)[[<span class="dv">1</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We do the same for latitude. However, we access the second value of each centroid with [[2]].</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>latitude<span class="ot">&lt;-</span><span class="fu">map_dbl</span>(nga_wp26391<span class="sc">$</span>geometry,<span class="sc">~</span><span class="fu">st_centroid</span>(.x)[[<span class="dv">2</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Since we have computed the longitude and latitude, we use cbind() to put longitude and latitude into the same object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>coords<span class="ot">&lt;-</span><span class="fu">cbind</span>(longitude,latitude)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(coords)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     longitude  latitude
[1,]  549364.0  123694.9
[2,]  547123.4  120376.5
[3,] 1189496.9 1059770.9
[4,]  489057.4  534262.6
[5,]  593718.2  113824.1
[6,]  642618.7  251222.3</code></pre>
</div>
</div>
<p>Now we are ready to proceed with our next steps to compute the fixed distance weighting scheme, followed by adaptive distance weighting scheme.</p>
</section>
<section id="determine-the-cut-off-distance" class="level4">
<h4 class="anchored" data-anchor-id="determine-the-cut-off-distance">Determine the cut-off distance</h4>
<p>First, we need to determine the upper bound for distance band by following the below steps:</p>
<ul>
<li><p>Return a matrix with the indices of points belonging to the set of k nearest neighbors of each area unit by using <em>knearneigh()</em> function of <strong>spdep</strong> package. In this example, we keep the default k=1 to find out the set of 1st nearest neighbors of each area unit.</p></li>
<li><p>Convert the knn object returned by the previous function <em>knearneigh()</em> into a list of neighbors of class nb with a list of integers specifying the neighbor IDs by using <em>knn2nb()</em> function of <strong>spdep</strong> package.</p></li>
<li><p>Return the length of neighbor relationship edges by using <em>nbdists()</em> of <strong>spdep</strong> package. The function returns in the unit of the coordinates if the coordinate system used is projected system. Else it will return in the unit of km.</p></li>
<li><p>Remove the list structure of the returned object by using <em>unlist()</em> structure.</p></li>
<li><p>Provide summary statistics with min, Q1, median, mean, Q3 and max values accordingly.</p></li>
</ul>
<p>Below are the below code chunks that handle all the above mentioned operations:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>k1<span class="ot">&lt;-</span><span class="fu">knn2nb</span>(<span class="fu">knearneigh</span>(coords))</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>k1dists<span class="ot">&lt;-</span><span class="fu">unlist</span>(<span class="fu">nbdists</span>(k1,coords))</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(k1dists)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   2669   12834   20304   22084   27783   72139 </code></pre>
</div>
</div>
<p>The summary report shows that the largest first nearest neighbor distance is 72139 m. So we use 73000 as the upper bound to ensure that all units have at least one neighbor.</p>
</section>
<section id="computing-fixed-distance-weight-matrix" class="level4">
<h4 class="anchored" data-anchor-id="computing-fixed-distance-weight-matrix">Computing fixed distance weight matrix</h4>
<p>Next, we will compute the distance weight matrix by using <em>dnearneigh()</em> with upper bound of 73000 m as shown in the below code chunks:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>wm_d73<span class="ot">&lt;-</span><span class="fu">dnearneigh</span>(coords,<span class="dv">0</span>,<span class="dv">73000</span>)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wm_d73)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 774 
Number of nonzero links: 18486 
Percentage nonzero weights: 3.085752 
Average number of links: 23.88372 
Link number distribution:

 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 
 4  9 11 17 35 35 29 28 34 38 28 20 17 27 12 17  7 13 13 13 24  5 12 12  5 15 
27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 
12  8 10 12 17  7  5 13  8  8 10 13 17 14  6  9  3  3  3  8  8 11  7  6  2  6 
53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 72 
 2  1  4  4  8  3  3  6  2  7  4  8  7  4  1  3  1 
4 least connected regions:
90 112 237 670 with 1 link
1 most connected region:
585 with 72 links</code></pre>
</div>
</div>
<p>For the above code chunks, <em>dnearneigh()</em> function identifies neighbours of region points by Euclidean distance with a distance band with lower d1= and upper d2= bounds controlled by the bounds= argument. Do take note that since we are using <strong>projected coordinate system</strong> in this exercise, the “longlat” argument was removed from the <em>dnearneigh()</em> function. How “longlat” argument works is that if <strong>unprojected coordinates system is used</strong> <strong>and</strong> <strong>either specified in the coordinates object x or with x as a two column matrix and longlat=TRUE</strong>, great circle distances in <strong>km</strong> will be calculated assuming the WGS84 reference ellipsoid. We can display the complete weight matrix by using <em>str()</em> in the below code chunk:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(wm_d73)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 774
 $ : int [1:64] 2 5 10 25 55 66 68 103 122 181 ...
 $ : int [1:62] 1 5 10 25 55 66 68 103 122 181 ...
 $ : int [1:2] 261 447
 $ : int [1:10] 12 20 257 263 446 454 466 641 690 695
 $ : int [1:56] 1 2 55 66 104 136 137 169 184 202 ...
 $ : int [1:21] 9 14 18 19 56 170 217 218 330 337 ...
 $ : int [1:20] 8 15 22 49 176 177 214 281 282 283 ...
 $ : int [1:34] 7 15 22 49 176 177 214 275 276 277 ...
 $ : int [1:27] 6 18 19 56 66 77 103 104 217 218 ...
 $ : int [1:64] 1 2 23 25 66 103 181 190 191 203 ...
 $ : int [1:23] 26 27 43 68 126 157 190 191 204 336 ...
 $ : int [1:11] 4 135 257 263 401 417 429 446 454 690 ...
 $ : int [1:13] 31 37 38 40 94 211 320 393 436 471 ...
 $ : int [1:24] 6 170 193 194 195 217 309 310 311 362 ...
 $ : int [1:27] 7 8 22 32 49 51 62 82 176 177 ...
 $ : int [1:38] 30 38 39 41 44 45 70 71 120 124 ...
 $ : int [1:34] 28 29 35 72 172 173 178 179 182 275 ...
 $ : int [1:30] 6 9 19 56 66 77 103 104 217 218 ...
 $ : int [1:42] 6 9 18 25 56 66 77 103 104 181 ...
 $ : int [1:7] 4 106 239 263 419 454 466
 $ : int [1:9] 60 61 162 269 484 520 578 596 626
 $ : int [1:32] 7 8 15 32 49 51 62 82 176 177 ...
 $ : int [1:64] 10 25 52 53 54 56 58 77 78 79 ...
 $ : int [1:5] 123 476 527 673 761
 $ : int [1:68] 1 2 10 19 23 54 56 66 77 103 ...
 $ : int [1:30] 11 27 43 68 157 190 191 204 336 370 ...
 $ : int [1:25] 11 26 43 68 157 191 204 336 370 371 ...
 $ : int [1:43] 17 29 35 70 71 124 172 173 178 179 ...
 $ : int [1:46] 17 28 35 70 71 120 124 172 173 178 ...
 $ : int [1:30] 16 38 39 40 41 44 45 175 185 186 ...
 $ : int [1:13] 13 37 94 158 210 211 212 289 308 561 ...
 $ : int [1:28] 15 22 49 51 62 82 177 196 207 214 ...
 $ : int [1:29] 47 111 130 142 145 155 166 219 227 233 ...
 $ : int [1:11] 42 86 104 136 137 213 375 553 559 733 ...
 $ : int [1:34] 17 28 29 72 172 173 178 179 182 275 ...
 $ : int [1:8] 50 107 247 408 432 455 681 759
 $ : int [1:21] 13 31 38 39 40 41 186 192 197 198 ...
 $ : int [1:25] 13 16 30 37 39 40 41 44 186 192 ...
 $ : int [1:27] 16 30 37 38 40 41 44 185 186 192 ...
 $ : int [1:21] 13 30 37 38 39 41 44 186 192 211 ...
 $ : int [1:24] 16 30 37 38 39 40 44 45 186 192 ...
 $ : int [1:21] 34 86 136 137 184 202 209 285 286 375 ...
 $ : int [1:19] 11 26 27 68 122 126 157 190 191 246 ...
 $ : int [1:28] 16 30 38 39 40 41 45 70 175 186 ...
 $ : int [1:27] 16 30 41 44 70 175 187 188 192 290 ...
 $ : int [1:12] 119 380 387 417 423 429 438 459 521 656 ...
 $ : int [1:25] 33 111 127 130 155 166 227 234 238 242 ...
 $ : int [1:12] 64 65 74 113 131 265 386 407 428 482 ...
 $ : int [1:31] 7 8 15 22 32 51 62 82 176 177 ...
 $ : int [1:5] 36 98 107 409 432
 $ : int [1:27] 15 22 32 49 62 82 177 207 214 284 ...
 $ : int [1:48] 23 53 54 57 58 77 78 79 80 165 ...
 $ : int [1:38] 23 52 54 57 58 78 79 80 165 189 ...
 $ : int [1:59] 23 25 52 53 56 57 58 77 78 79 ...
 $ : int [1:34] 1 2 5 68 122 157 169 184 190 203 ...
 $ : int [1:51] 6 9 18 19 23 25 54 66 77 78 ...
 $ : int [1:35] 52 53 54 58 78 79 80 165 189 197 ...
 $ : int [1:38] 23 52 53 54 57 78 79 165 189 197 ...
 $ : int [1:5] 128 129 493 700 748
 $ : int [1:14] 21 61 158 269 310 311 561 563 578 589 ...
 $ : int [1:11] 21 60 162 268 269 484 578 589 592 596 ...
 $ : int [1:28] 15 22 32 49 51 82 177 196 207 214 ...
 $ : int [1:5] 384 416 467 765 772
 $ : int [1:7] 48 65 74 113 131 265 407
 $ : int [1:11] 48 64 74 109 113 265 386 407 683 701 ...
 $ : int [1:48] 1 2 5 9 10 18 19 25 56 103 ...
 $ : int [1:26] 72 120 124 179 182 304 305 339 346 347 ...
 $ : int [1:30] 1 2 11 26 27 43 55 122 157 190 ...
 $ : int [1:8] 140 146 248 274 473 500 512 513
 $ : int [1:44] 16 28 29 44 45 71 120 124 172 173 ...
 $ : int [1:50] 16 28 29 70 120 124 172 173 175 178 ...
 $ : int [1:20] 17 35 67 182 348 361 374 378 404 566 ...
 $ : int [1:6] 361 374 377 404 665 666
 $ : int [1:15] 48 64 65 109 113 116 251 265 672 683 ...
 $ : int [1:15] 110 229 255 258 272 373 382 398 422 433 ...
 $ : int [1:9] 254 287 427 459 470 547 647 677 751
 $ : int [1:60] 9 18 19 23 25 52 54 56 78 79 ...
 $ : int [1:52] 23 52 53 54 56 57 58 77 79 80 ...
 $ : int [1:57] 23 52 53 54 56 57 58 77 78 80 ...
 $ : int [1:41] 23 52 53 54 57 77 78 79 165 189 ...
 $ : int [1:20] 99 145 156 227 233 242 255 270 426 449 ...
 $ : int [1:21] 15 22 32 49 51 62 177 207 214 297 ...
 $ : int [1:6] 132 258 383 414 529 767
 $ : int [1:3] 148 437 692
 $ : int [1:39] 101 105 130 142 145 155 156 219 235 242 ...
 $ : int [1:17] 34 42 136 137 184 202 285 286 499 538 ...
 $ : int [1:19] 147 149 151 221 226 245 267 399 410 415 ...
 $ : int [1:5] 150 489 648 700 714
 $ : int [1:12] 100 107 159 260 408 458 463 542 674 676 ...
 $ : int 237
 $ : int [1:3] 160 271 406
 $ : int [1:11] 95 119 390 391 392 423 487 642 656 668 ...
 $ : int [1:3] 354 607 665
 $ : int [1:7] 13 31 158 436 561 596 709
 $ : int [1:10] 92 390 391 392 405 423 469 656 708 770
 $ : int [1:17] 97 108 139 167 168 350 389 403 412 420 ...
 $ : int [1:14] 96 108 114 139 147 168 389 403 412 420 ...
 $ : int [1:5] 50 153 231 432 696
 $ : int [1:18] 81 145 154 167 227 233 255 270 426 449 ...
  [list output truncated]
 - attr(*, "class")= chr "nb"
 - attr(*, "region.id")= chr [1:774] "1" "2" "3" "4" ...
 - attr(*, "call")= language dnearneigh(x = coords, d1 = 0, d2 = 73000)
 - attr(*, "dnn")= num [1:2] 0 73000
 - attr(*, "bounds")= chr [1:2] "GE" "LE"
 - attr(*, "nbtype")= chr "distance"
 - attr(*, "sym")= logi TRUE</code></pre>
</div>
</div>
<p>Next, <em>nb2listw()</em> is used to convert th nb object into spatial weights object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>wm73_lw<span class="ot">&lt;-</span><span class="fu">nb2listw</span>(wm_d73,<span class="at">style=</span><span class="st">"W"</span>)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wm73_lw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Characteristics of weights list object:
Neighbour list object:
Number of regions: 774 
Number of nonzero links: 18486 
Percentage nonzero weights: 3.085752 
Average number of links: 23.88372 
Link number distribution:

 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 
 4  9 11 17 35 35 29 28 34 38 28 20 17 27 12 17  7 13 13 13 24  5 12 12  5 15 
27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 
12  8 10 12 17  7  5 13  8  8 10 13 17 14  6  9  3  3  3  8  8 11  7  6  2  6 
53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 72 
 2  1  4  4  8  3  3  6  2  7  4  8  7  4  1  3  1 
4 least connected regions:
90 112 237 670 with 1 link
1 most connected region:
585 with 72 links

Weights style: W 
Weights constants summary:
    n     nn  S0       S1       S2
W 774 599076 774 126.9629 3125.191</code></pre>
</div>
</div>
<p>From the above summary, each area unit has around 23.88 neighbors on average if we cap the upper d2= bound as 73000. Notice that most connected region has 72 links. This is an insanely big number. As seen in the map, Nigeria is densely settled with many small area units in some regions. This method therefore shows a major drawback as it masks subtle local variations and smooths out any variations if the one area has too many neighbors.</p>
<p>Therefore, in this case, we will also consider adaptive weighting schemes to limit the number of neighbors. This may prove to be more superior in the case of Nigeria as this scheme can adjust itself according to the density of the data.</p>
</section>
<section id="computing-adaptive-distance-weight-matrix" class="level4">
<h4 class="anchored" data-anchor-id="computing-adaptive-distance-weight-matrix">Computing adaptive distance weight matrix</h4>
<p>In the below code chunks, we control the number of neighbors directly using k-nearest neighbors, either accepting asymmetric neighbors or imposing symmetry. In this exercise, we can start with k=8.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>knn<span class="ot">&lt;-</span><span class="fu">knn2nb</span>(<span class="fu">knearneigh</span>(coords,<span class="at">k=</span><span class="dv">8</span>))</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>knn</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 774 
Number of nonzero links: 6192 
Percentage nonzero weights: 1.033592 
Average number of links: 8 
Non-symmetric neighbours list</code></pre>
</div>
</div>
<p>From the above table summary, we can see that each area unit has exactly 8 neighbors, no more no less!</p>
<p>Next, in the below code chunk, we create a row standardized spatial weight matrix in “W” style using the <em>nb2listw()</em> function. The reason why we should chose “W” over “B” was because the spatially lagged variable in this case is proportion/rate, which should be capped at 1. If “B” was used, spatially lagged variables <code>pct nonfunctional</code> in the later parts may end up larger than 1, which does not make any sense for proportion/rate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>knn_lw<span class="ot">&lt;-</span><span class="fu">nb2listw</span>(knn,<span class="at">style=</span><span class="st">"W"</span>)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(knn_lw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Characteristics of weights list object:
Neighbour list object:
Number of regions: 774 
Number of nonzero links: 6192 
Percentage nonzero weights: 1.033592 
Average number of links: 8 
Non-symmetric neighbours list
Link number distribution:

  8 
774 
774 least connected regions:
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647 648 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665 666 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683 684 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701 702 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719 720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737 738 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773 774 with 8 links
774 most connected regions:
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647 648 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665 666 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683 684 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701 702 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719 720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737 738 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773 774 with 8 links

Weights style: W 
Weights constants summary:
    n     nn  S0       S1       S2
W 774 599076 774 174.2812 3155.312</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>knn_lw</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Characteristics of weights list object:
Neighbour list object:
Number of regions: 774 
Number of nonzero links: 6192 
Percentage nonzero weights: 1.033592 
Average number of links: 8 
Non-symmetric neighbours list

Weights style: W 
Weights constants summary:
    n     nn  S0       S1       S2
W 774 599076 774 174.2812 3155.312</code></pre>
</div>
</div>
<p>For the rest of the analysis, we will be using adaptive distance weight matrix as the distribution of data varies across our study area.</p>
</section>
</section>
</section>
<section id="global-spatial-autocorrelation-morans-i" class="level2">
<h2 class="anchored" data-anchor-id="global-spatial-autocorrelation-morans-i">Global Spatial Autocorrelation: Moran’s I</h2>
<section id="morans-i-test" class="level3">
<h3 class="anchored" data-anchor-id="morans-i-test">Moran’s I test</h3>
<p>The below code chunks perform Moran’s I statistics calculation by using <em>moran.test()</em> function of <strong>spdep</strong> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">moran.test</span>(nga_wp26391<span class="sc">$</span><span class="st">`</span><span class="at">pct nonfunctional</span><span class="st">`</span>,<span class="at">listw=</span>knn_lw,<span class="at">zero.policy =</span> <span class="cn">TRUE</span>,<span class="at">na.action=</span>na.omit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Moran I test under randomisation

data:  nga_wp26391$`pct nonfunctional`  
weights: knn_lw    

Moran I statistic standard deviate = 27.282, p-value &lt; 2.2e-16
alternative hypothesis: greater
sample estimates:
Moran I statistic       Expectation          Variance 
     0.4613882839     -0.0012936611      0.0002876085 </code></pre>
</div>
</div>
<p>From the above summary table, we can see that Moran’s I (Z-value) of 0.46 is positive, which means observations tend to be clustered and similar.</p>
<p>We can also conduct a permutation test for Moran’s I statistics by using <em>moran.mc()</em> of <strong>spdep</strong>. A total of 1000 simulations will be performed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>bperm<span class="ot">&lt;-</span><span class="fu">moran.mc</span>(nga_wp26391<span class="sc">$</span><span class="st">`</span><span class="at">pct nonfunctional</span><span class="st">`</span>,<span class="at">listw=</span>knn_lw,<span class="at">nsim=</span><span class="dv">999</span>,<span class="at">zero.policy=</span><span class="cn">TRUE</span>,<span class="at">na.action=</span>na.omit)</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>bperm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Monte-Carlo simulation of Moran I

data:  nga_wp26391$`pct nonfunctional` 
weights: knn_lw  
number of simulations + 1: 1000 

statistic = 0.46139, observed rank = 1000, p-value = 0.001
alternative hypothesis: greater</code></pre>
</div>
</div>
<p>From the output above, using Monte-Carlo simulation of Moran’s I with 1000 observation, the statistics of 0.46 is somehow similar to our findings when calculating the global Moran’s I statistics above. The area units are clustered and observations tend to be similar.</p>
</section>
<section id="gearys-c" class="level3">
<h3 class="anchored" data-anchor-id="gearys-c">Geary’s c</h3>
<p>We can also consider Geary’s c test in our analysis.</p>
<p>The code chunks below performs Geary’s c test for spatial autocorrelation by using <em>geary.test()</em> function of <strong>spdep</strong> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">geary.test</span>(nga_wp26391<span class="sc">$</span><span class="st">`</span><span class="at">pct nonfunctional</span><span class="st">`</span>,<span class="at">listw=</span>knn_lw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Geary C test under randomisation

data:  nga_wp26391$`pct nonfunctional` 
weights: knn_lw 

Geary C statistic standard deviate = 26.256, p-value &lt; 2.2e-16
alternative hypothesis: Expectation greater than statistic
sample estimates:
Geary C statistic       Expectation          Variance 
      0.526234882       1.000000000       0.000325599 </code></pre>
</div>
</div>
<p>From the above table summary, we can see that Geary c statistics (z-value) is 0.526234882, which is less than 1. We conclude that the area units are clustered and observations tend to be similar.</p>
<p>We can also perform Monte-Carlo simulation of Geary’s c test with 1000 observations with the below code chunks:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>bperm<span class="ot">&lt;-</span><span class="fu">geary.mc</span>(nga_wp26391<span class="sc">$</span><span class="st">`</span><span class="at">pct nonfunctional</span><span class="st">`</span>,<span class="at">listw=</span>knn_lw,<span class="at">nsim=</span><span class="dv">999</span>)</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>bperm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Monte-Carlo simulation of Geary C

data:  nga_wp26391$`pct nonfunctional` 
weights: knn_lw 
number of simulations + 1: 1000 

statistic = 0.52623, observed rank = 1, p-value = 0.001
alternative hypothesis: greater</code></pre>
</div>
</div>
<p>The output for both the Geary’s c Test and Monte-Carlo simulation are both similar. Both shows that there were clusters and observations tend to be similar.</p>
<p>We notice that both Moran’s I Statistics and Geary’s c statistics yield the same conclusion. C approaches 0 and I approaches 1 when similar values are clustered.</p>
</section>
</section>
<section id="cluster-and-outlier-analysis" class="level2">
<h2 class="anchored" data-anchor-id="cluster-and-outlier-analysis">Cluster and Outlier Analysis</h2>
<p>Local Indicators of Spatial Association or LISA in short are statistics that evaluate the existence of clusters and/or outliers in the spatial arrangement of a given variable. In this section, we will apply appropriate LISA, especially local Moran’s I to detect clusters and/or outliers on the proportion of number of non-functional water points to the total number of water points in Nigeria.</p>
<section id="computing-local-morans-i" class="level3">
<h3 class="anchored" data-anchor-id="computing-local-morans-i">Computing local Moran’s I</h3>
<p>The function localmoran() of <strong>spdep</strong> package is used to calculate the local Moran’s I statistics. It computes Ii values, given a set of zi values and a listw object (in this case, knn_lw)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>fips<span class="ot">&lt;-</span><span class="fu">order</span>(nga_wp26391<span class="sc">$</span>shapeName)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>localMI<span class="ot">&lt;-</span><span class="fu">localmoran</span>(nga_wp26391<span class="sc">$</span><span class="st">`</span><span class="at">pct nonfunctional</span><span class="st">`</span>,knn_lw)</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(localMI)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Ii          E.Ii     Var.Ii     Z.Ii Pr(z != E(Ii))
1 0.6758946 -0.0008481017 0.08124087 2.374304   1.758207e-02
2 0.6206028 -0.0005236472 0.05017720 2.772853   5.556728e-03
3 2.9220515 -0.0037801442 0.36104279 4.869339   1.119723e-06
4 0.2169765 -0.0016485516 0.15779059 0.550376   5.820615e-01
5 0.8924913 -0.0007647464 0.07326225 3.300166   9.662752e-04
6 0.5741337 -0.0009383859 0.08988120 1.918173   5.508904e-02</code></pre>
</div>
</div>
<p>localmoran() function returns a matrix of values whose columns are:</p>
<ul>
<li><p>Ii: the local Moran’s I statistics</p></li>
<li><p>E.Ii: the expectation of local Moran’s I statistics under the randomization hypothesis</p></li>
<li><p>Var.Ii: the variance of local Moran’s I statistics under the randomization hypothesis</p></li>
<li><p>Z.Ii: the standard deviate of local Moran’s I statistics</p></li>
<li><p>Pr(): the p-value of local Moran’s I statistics</p></li>
</ul>
</section>
<section id="mapping-the-local-morans-i-statistics" class="level3">
<h3 class="anchored" data-anchor-id="mapping-the-local-morans-i-statistics">Mapping the local Moran’s I statistics</h3>
<p>Before mapping the local Moran’s I map, we will need to append the local Moran’s I dataframe (i.e.&nbsp;localMI) onto the nga_wp26391 SpatialPolygonDataFrame. The ouput SpatialPolygonDataFrame will then be called nga.localMI. The code chunks below perform the task:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>nga.localMI<span class="ot">&lt;-</span><span class="fu">cbind</span>(nga_wp26391,localMI)<span class="sc">%&gt;%</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Pr.Ii=</span>Pr.z....E.Ii..)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="mapping-local-morans-i-statistics" class="level3">
<h3 class="anchored" data-anchor-id="mapping-local-morans-i-statistics">Mapping local Moran’s I statistics</h3>
<p>We can plot the local Moran’s I statistics using choropleth mapping functions of tmap package in the below code chunks:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(nga.localMI)<span class="sc">+</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col=</span><span class="st">"Ii"</span>,<span class="at">style=</span><span class="st">"pretty"</span>,<span class="at">title=</span><span class="st">"Local Moran's I Statistics"</span>)<span class="sc">+</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha=</span><span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex1_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="mapping-local-morans-i-p-values" class="level3">
<h3 class="anchored" data-anchor-id="mapping-local-morans-i-p-values">Mapping local Moran’s I p-values</h3>
<p>The code chunks below produce a choropleth map of Moran’s I p-values by using functions of tmap package:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(nga.localMI)<span class="sc">+</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col=</span><span class="st">"Pr.Ii"</span>,<span class="at">breaks=</span><span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>,<span class="fl">0.001</span>,<span class="fl">0.01</span>,<span class="fl">0.05</span>,<span class="fl">0.1</span>,<span class="cn">Inf</span>),<span class="at">palette=</span><span class="st">"-Blues"</span>,<span class="at">title=</span><span class="st">"Local Moran's I p-values"</span>)<span class="sc">+</span></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha=</span><span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex1_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="mapping-both-local-morans-i-statistics-and-p-values" class="level3">
<h3 class="anchored" data-anchor-id="mapping-both-local-morans-i-statistics-and-p-values">Mapping both local Moran’s I statistics and p-values</h3>
<p>For effective interpretation, we can plot both Moran’s I statistics and its corresponding p-values maps side by side using the below code chunks.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>localMI.map<span class="ot">&lt;-</span><span class="fu">tm_shape</span>(nga.localMI)<span class="sc">+</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col=</span><span class="st">"Ii"</span>,<span class="at">style=</span><span class="st">"pretty"</span>,<span class="at">title=</span><span class="st">"Local Moran's I Statistics"</span>)<span class="sc">+</span></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha=</span><span class="fl">0.5</span>)</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>pvalue.map<span class="ot">&lt;-</span><span class="fu">tm_shape</span>(nga.localMI)<span class="sc">+</span></span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col=</span><span class="st">"Pr.Ii"</span>,<span class="at">breaks=</span><span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>,<span class="fl">0.001</span>,<span class="fl">0.01</span>,<span class="fl">0.05</span>,<span class="fl">0.1</span>,<span class="cn">Inf</span>),<span class="at">palette=</span><span class="st">"-Blues"</span>,<span class="at">title=</span><span class="st">"Local Moran's I p-values"</span>)<span class="sc">+</span></span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha=</span><span class="fl">0.5</span>)</span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(localMI.map,pvalue.map,<span class="at">asp=</span><span class="dv">1</span>,<span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex1_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="interpretation-of-local-morans-statistics" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-of-local-morans-statistics">Interpretation of Local Moran’s statistics</h3>
<p>If the p-value for the feature is small enough to be considered statistically significant and local MI statistics are positive if location i is associated with relatively high values of the surrounding area, the location is a cluster.</p>
<p>If the p-value for the feature is small enough to be considered statistically significant and local MI statistics are negative if location i is associated with relatively low values of the surrounding area, the location is an outlier.</p>
</section>
</section>
<section id="creating-a-lisa-cluster-map" class="level2">
<h2 class="anchored" data-anchor-id="creating-a-lisa-cluster-map">Creating a LISA Cluster Map</h2>
<section id="plotting-moran-scatterplot" class="level3">
<h3 class="anchored" data-anchor-id="plotting-moran-scatterplot">Plotting Moran scatterplot</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>nci<span class="ot">&lt;-</span><span class="fu">moran.plot</span>(nga_wp26391<span class="sc">$</span><span class="st">`</span><span class="at">pct nonfunctional</span><span class="st">`</span>,knn_lw,<span class="at">xlab=</span><span class="st">"pct nonfunctional"</span>,<span class="at">ylab=</span><span class="st">"Spatially lag pct nonfunctional"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex1_files/figure-html/unnamed-chunk-48-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The slope of the linear regression of the lagged variable of pct non-functional versus the original pct non-functional is equivalent to the Moran’s I score.</p>
</section>
<section id="plotting-moran-scatterplot-with-standardized-variable" class="level3">
<h3 class="anchored" data-anchor-id="plotting-moran-scatterplot-with-standardized-variable">Plotting Moran scatterplot with standardized variable</h3>
<p>First we will use scale() function to center and scale the the variable. Centering is done by subtracting the column means (omitting NA) of x from their corresponding columns. Scaling is done by dividing (centered) columns of x by their standard deviations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>nga_wp26391<span class="sc">$</span>Z.pct_nonfunctional <span class="ot">&lt;-</span> <span class="fu">scale</span>(nga_wp26391<span class="sc">$</span><span class="st">`</span><span class="at">pct nonfunctional</span><span class="st">`</span>)<span class="sc">%&gt;%</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>  as.vector</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As.vector() function ensures that the output’s data type is a vector which can map into our dataframe.</p>
<p>We will then proceed to plot the Moran scatterplot again by using the below code chunks:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>nci2<span class="ot">&lt;-</span><span class="fu">moran.plot</span>(nga_wp26391<span class="sc">$</span>Z.pct_nonfunctional,knn_lw,<span class="at">labels=</span><span class="fu">as.character</span>(nga_wp26391<span class="sc">$</span>shapeName),<span class="at">xlab=</span><span class="st">"z-pct nonfunctional"</span>,<span class="at">ylab=</span><span class="st">"Spatially lag z-pct nonfunctional"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex1_files/figure-html/unnamed-chunk-50-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="preparing-lisa-map-classes" class="level3">
<h3 class="anchored" data-anchor-id="preparing-lisa-map-classes">Preparing LISA map classes</h3>
<p>The code chunks below show the step to prepare a LISA map</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>quadrant<span class="ot">&lt;-</span><span class="fu">vector</span>(<span class="at">mode=</span><span class="st">"numeric"</span>,<span class="at">length=</span><span class="fu">nrow</span>(localMI))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, we derive the spatially lagged variable (i.e.&nbsp;pct nonfunctional) and center the spatially lagged variable around its mean.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>nga_wp26391<span class="sc">$</span>lag_pct_nonfunctional<span class="ot">&lt;-</span><span class="fu">lag.listw</span>(knn_lw,nga_wp26391<span class="sc">$</span><span class="st">`</span><span class="at">pct nonfunctional</span><span class="st">`</span>)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>DV<span class="ot">&lt;-</span>nga_wp26391<span class="sc">$</span>lag_pct_nonfunctional<span class="sc">-</span><span class="fu">mean</span>(nga_wp26391<span class="sc">$</span>lag_pct_nonfunctional)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This will be followed by centering the local Moran’s I around its mean.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>LM_I<span class="ot">&lt;-</span>localMI[,<span class="dv">1</span>]<span class="sc">-</span><span class="fu">mean</span>(localMI[,<span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We also need to set significant level for the local Moran’s I statistics:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>signif<span class="ot">&lt;-</span><span class="fl">0.05</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>These four command lines define low-low (1st quadrant), low-high (2nd quadrant), high-low (3rd quadrant), high-high (4th quadrant):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>quadrant[DV<span class="sc">&lt;</span><span class="dv">0</span> <span class="sc">&amp;</span> LM_I<span class="sc">&gt;</span><span class="dv">0</span>]<span class="ot">&lt;-</span><span class="dv">1</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>quadrant[DV<span class="sc">&gt;</span><span class="dv">0</span> <span class="sc">&amp;</span> LM_I<span class="sc">&lt;</span><span class="dv">0</span>]<span class="ot">&lt;-</span><span class="dv">2</span></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>quadrant[DV<span class="sc">&lt;</span><span class="dv">0</span> <span class="sc">&amp;</span> LM_I<span class="sc">&lt;</span><span class="dv">0</span>]<span class="ot">&lt;-</span><span class="dv">3</span></span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>quadrant[DV<span class="sc">&gt;</span><span class="dv">0</span> <span class="sc">&amp;</span> LM_I<span class="sc">&gt;</span><span class="dv">0</span>]<span class="ot">&lt;-</span><span class="dv">4</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We will then place all those insignificant Moran in the quadrant 0.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>quadrant[localMI[,<span class="dv">5</span>]<span class="sc">&gt;</span>signif]<span class="ot">&lt;-</span><span class="dv">0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We combine all the above codes in the below code chunks as shown below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>quadrant<span class="ot">&lt;-</span><span class="fu">vector</span>(<span class="at">mode=</span><span class="st">"numeric"</span>,<span class="at">length=</span><span class="fu">nrow</span>(localMI))</span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>nga_wp26391<span class="sc">$</span>lag_pct_nonfunctional<span class="ot">&lt;-</span><span class="fu">lag.listw</span>(knn_lw,nga_wp26391<span class="sc">$</span><span class="st">`</span><span class="at">pct nonfunctional</span><span class="st">`</span>)</span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>DV<span class="ot">&lt;-</span>nga_wp26391<span class="sc">$</span>lag_pct_nonfunctional<span class="sc">-</span><span class="fu">mean</span>(nga_wp26391<span class="sc">$</span>lag_pct_nonfunctional)</span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>LM_I<span class="ot">&lt;-</span>localMI[,<span class="dv">1</span>]<span class="sc">-</span><span class="fu">mean</span>(localMI[,<span class="dv">1</span>])</span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a>signif<span class="ot">&lt;-</span><span class="fl">0.05</span></span>
<span id="cb79-6"><a href="#cb79-6" aria-hidden="true" tabindex="-1"></a>quadrant[DV<span class="sc">&lt;</span><span class="dv">0</span> <span class="sc">&amp;</span> LM_I<span class="sc">&gt;</span><span class="dv">0</span>]<span class="ot">&lt;-</span><span class="dv">1</span></span>
<span id="cb79-7"><a href="#cb79-7" aria-hidden="true" tabindex="-1"></a>quadrant[DV<span class="sc">&gt;</span><span class="dv">0</span> <span class="sc">&amp;</span> LM_I<span class="sc">&lt;</span><span class="dv">0</span>]<span class="ot">&lt;-</span><span class="dv">2</span></span>
<span id="cb79-8"><a href="#cb79-8" aria-hidden="true" tabindex="-1"></a>quadrant[DV<span class="sc">&lt;</span><span class="dv">0</span> <span class="sc">&amp;</span> LM_I<span class="sc">&lt;</span><span class="dv">0</span>]<span class="ot">&lt;-</span><span class="dv">3</span></span>
<span id="cb79-9"><a href="#cb79-9" aria-hidden="true" tabindex="-1"></a>quadrant[DV<span class="sc">&gt;</span><span class="dv">0</span> <span class="sc">&amp;</span> LM_I<span class="sc">&gt;</span><span class="dv">0</span>]<span class="ot">&lt;-</span><span class="dv">4</span></span>
<span id="cb79-10"><a href="#cb79-10" aria-hidden="true" tabindex="-1"></a>quadrant[localMI[,<span class="dv">5</span>]<span class="sc">&gt;</span>signif]<span class="ot">&lt;-</span><span class="dv">0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="plotting-lisa-map" class="level3">
<h3 class="anchored" data-anchor-id="plotting-lisa-map">Plotting LISA Map</h3>
<p>We can build a LISA map by using the below code chunks:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>nga.localMI<span class="sc">$</span>quadrant<span class="ot">&lt;-</span>quadrant</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>colors<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"#ffffff"</span>, <span class="st">"#2c7bb6"</span>, <span class="st">"#abd9e9"</span>, <span class="st">"#fdae61"</span>, <span class="st">"#d7191c"</span>)</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>clusters<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"Insignificant"</span>, <span class="st">"Low-Low"</span>, <span class="st">"Low-High"</span>, <span class="st">"High-Low"</span>, <span class="st">"High-High"</span>)</span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(nga.localMI)<span class="sc">+</span></span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col=</span><span class="st">"quadrant"</span>,<span class="at">style=</span><span class="st">"cat"</span>,<span class="at">palette=</span>colors[<span class="fu">c</span>(<span class="fu">sort</span>(<span class="fu">unique</span>(quadrant)))<span class="sc">+</span><span class="dv">1</span>],<span class="at">labels=</span>clusters[<span class="fu">c</span>(<span class="fu">sort</span>(<span class="fu">unique</span>(quadrant)))<span class="sc">+</span><span class="dv">1</span>],<span class="at">popup.vars =</span> <span class="fu">c</span>(<span class="st">""</span>))<span class="sc">+</span></span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_view</span>(<span class="at">set.zoom.limits =</span> <span class="fu">c</span>(<span class="dv">11</span>,<span class="dv">17</span>))<span class="sc">+</span><span class="fu">tm_borders</span>(<span class="at">alpha=</span><span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex1_files/figure-html/unnamed-chunk-58-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>For effective interpretation, we plot both the thematic map by <code>pct nonfunctional</code> and the LISA map side by side.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>pct_nonfunctional<span class="ot">&lt;-</span><span class="fu">qtm</span>(nga_wp26391,<span class="st">"pct nonfunctional"</span>)</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>nga.localMI<span class="sc">$</span>quadrant<span class="ot">&lt;-</span>quadrant</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>colors<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"#ffffff"</span>, <span class="st">"#2c7bb6"</span>, <span class="st">"#abd9e9"</span>, <span class="st">"#fdae61"</span>, <span class="st">"#d7191c"</span>)</span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>clusters<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"Insignificant"</span>, <span class="st">"Low-Low"</span>, <span class="st">"Low-High"</span>, <span class="st">"High-Low"</span>, <span class="st">"High-High"</span>)</span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>LISAmap<span class="ot">&lt;-</span><span class="fu">tm_shape</span>(nga.localMI)<span class="sc">+</span></span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col=</span><span class="st">"quadrant"</span>,<span class="at">style=</span><span class="st">"cat"</span>,<span class="at">palette=</span>colors[<span class="fu">c</span>(<span class="fu">sort</span>(<span class="fu">unique</span>(quadrant)))<span class="sc">+</span><span class="dv">1</span>],<span class="at">labels=</span>clusters[<span class="fu">c</span>(<span class="fu">sort</span>(<span class="fu">unique</span>(quadrant)))<span class="sc">+</span><span class="dv">1</span>],<span class="at">popup.vars =</span> <span class="fu">c</span>(<span class="st">""</span>))<span class="sc">+</span></span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_view</span>(<span class="at">set.zoom.limits =</span> <span class="fu">c</span>(<span class="dv">11</span>,<span class="dv">17</span>))<span class="sc">+</span><span class="fu">tm_borders</span>(<span class="at">alpha=</span><span class="fl">0.5</span>)</span>
<span id="cb81-8"><a href="#cb81-8" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(pct_nonfunctional,LISAmap,<span class="at">asp=</span><span class="dv">1</span>,<span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex1_files/figure-html/unnamed-chunk-59-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the LISA cluster plots, we notice that significant classification appears in all four quadrants: Low-Low, Low-High, High-Low and High-High . However there was one big limitation that NA values have been masked as 0. For some areas, having no non-functional water points or 0% rate of non-functional water points was in fact due to having no water points at all, not because the maintenance of water points were excellent in those regions.</p>
</section>
</section>
<section id="hot-spot-and-cold-spot-analysis" class="level2">
<h2 class="anchored" data-anchor-id="hot-spot-and-cold-spot-analysis">Hot Spot and Cold Spot Analysis</h2>
<p>Besides detecting clusters and outliers, local spatial statistics can also be used to detect hot spots and cold spots.</p>
<p>Since we choose the distance based spatial weights method over the contiguity based spatial weights, we can explore the option to use Getis and Ord’s G-Statistics to detect other spatial abnormalities. This statistics looks at neighbors within a defined proximity to identify where either statistically significant high or low clusters spatially. Here, the statistically significant hot spots are recognized as areas of high proportion of non-functional water points where other areas within their neighborhood range also share high values of non-functional water point rate.</p>
<section id="gi-statistics-using-adaptive-distance" class="level3">
<h3 class="anchored" data-anchor-id="gi-statistics-using-adaptive-distance">Gi statistics using adaptive distance</h3>
<p>The below code chunks compute the GI statistics based on adaptive distance spatial weight matrix.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>fips<span class="ot">&lt;-</span><span class="fu">order</span>(nga_wp26391<span class="sc">$</span>shapeName)</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>gi.adaptive<span class="ot">&lt;-</span><span class="fu">localG</span>(nga_wp26391<span class="sc">$</span><span class="st">`</span><span class="at">pct nonfunctional</span><span class="st">`</span>,knn_lw)</span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>gi.adaptive</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1]  2.374303998  2.772852644 -4.869338828  0.550375967  3.300166403
  [6] -1.918173288 -1.162901369 -1.014522250 -0.430477172  0.171685244
 [11]  0.132585130 -0.028991233  2.665262882 -0.501305940 -2.091233562
 [16] -0.459734611 -1.413676386 -0.037722987 -0.726580453 -0.155012340
 [21]  3.748629533 -2.908993368 -1.779361638  1.747339784  0.640239850
 [26] -2.022338545  0.506028678  0.911818009 -0.905274894 -0.543447781
 [31]  3.056250463 -3.148256782 -2.757071737  1.696116531 -1.135547565
 [36]  1.395691479  2.395479078  1.087862667  0.720302212  1.146769559
 [41]  0.231244309  2.414053900 -0.829644101  0.325926693  2.016115264
 [46]  0.631731771 -2.878594146  1.504218840 -3.134925107  0.986433120
 [51] -3.012905091 -1.950482789 -0.515354445 -2.456553981  0.983092852
 [56] -1.063237779  1.142578459 -0.219806501 -0.348868121  3.473610973
 [61]  4.400951792 -2.942366219 -0.086621764  1.349787937  0.748079750
 [66]  1.728984394  0.679313176 -1.901922242  0.375562029  1.660566938
 [71]  0.690026158 -0.904642723 -1.154580270  1.243397778 -3.055785419
 [76]  0.878271333 -1.903086667 -0.568097299 -1.608134988 -0.939223207
 [81] -2.218725332 -1.817199151 -3.014709556  3.381321517 -2.736012201
 [86]  3.300706384 -1.071196382 -0.229533602 -1.189795631 -0.062807694
 [91] -4.457448712 -0.641220193 -0.323512062  3.820430793 -0.701154032
 [96] -0.289084237 -0.653643552 -1.849720546 -1.984909277  0.441496156
[101] -1.936606706 -0.209570540  0.121301257  1.472412292 -3.050541115
[106]  0.783188373  0.366816079 -1.211352695  0.784787931 -2.847570772
[111] -2.457963127  1.161329664  1.885831753 -1.708214935 -2.449779569
[116] -0.186103300 -1.865796795  0.363047479  0.105164975  1.250516395
[121]  3.310544709 -0.521886314  1.878233733  1.081670665  0.056453948
[126]  1.592743086 -2.585941892 -0.285938349 -1.286502198 -1.909972072
[131]  2.082910373 -3.098578541 -0.131607929  3.790699133  0.128951275
[136]  2.558936511  2.198319485 -0.022128197 -1.369274277 -2.977596817
[141]  1.009645896 -2.609667406 -3.304513726 -0.967521764 -2.977784574
[146] -4.079228176 -2.053695831  2.229576155  0.162039076 -0.354843126
[151] -0.066582234  0.616189245 -1.864909987 -0.264985037 -1.346759909
[156] -1.898933015 -3.196092833  3.254730359 -1.509717425 -4.457448712
[161] -1.625606016  2.908478454  0.511836812  1.520324736 -2.265997650
[166] -2.530440620  0.329593503 -2.308809404  2.952841665 -2.104587623
[171]  0.266119716  0.720702398  0.268123865  0.429441930  0.843554137
[176] -1.790173102 -0.606398393 -0.565568114 -0.501814166  2.248657559
[181]  1.202071639 -0.440942958  2.688629520  4.269940539  1.093375793
[186]  1.348554697  1.067495432  0.214565970 -2.911092293 -0.840343261
[191] -1.463164615  1.201508979 -1.442678887 -1.956255568 -2.104040977
[196] -1.349596486  3.265022499  3.992267477  2.988286930  3.152995233
[201]  3.026889362  4.139019107  4.398566150  0.034363320  2.734132025
[206]  2.942077338 -2.925955872  4.762687416  3.650537574  3.074065269
[211]  2.406065852  3.015500351 -0.293824306 -1.069141557 -1.693125598
[216]  0.489426693 -2.329145556 -1.181913119 -1.997139084  2.088217592
[221] -0.354341526  0.819875699 -1.177514641  2.088670485 -2.295632213
[226]  0.351003688 -2.197400947  1.499164666 -2.693659687 -1.830693952
[231] -1.124818818 -0.229824636 -2.998389934 -1.866388898 -2.378386332
[236]  0.195728060  0.064889669 -2.061163312  0.229740643  0.290737771
[241] -3.814150023 -2.718394681 -1.191269543 -1.770042653  1.992004855
[246] -1.580591473  2.361306770 -1.417494523  0.224708772 -4.030539009
[251]  1.248989459 -2.180881958 -0.448833382  1.025320747 -3.167743426
[256]  0.632418522  0.814310133 -2.271722882 -0.455215383 -2.017360473
[261] -4.493319023  0.887709024  0.550506443 -2.278753189  0.975539577
[266] -2.135537448 -2.127032908  1.126104186  2.134219418 -0.661714672
[271] -2.374320195 -3.616015269 -1.622813821  1.102356627 -0.367830648
[276] -0.944717212 -1.344961985 -0.631396519 -1.255376429  1.995419523
[281] -0.822434129 -0.946147828 -1.168149570 -0.785715620  4.035391070
[286]  3.933710425  0.101875382  3.963205261  3.137973000  2.829429594
[291] -0.946812483 -0.153725786 -1.678895776 -2.734032543 -1.146193703
[296]  0.911341530 -3.277268923  0.391629358  0.909565522  1.078754606
[301]  2.447631569  0.625602983  1.676224372  1.748301150  0.876705631
[306] -2.572378481  2.002783889  0.433425585 -3.647004540  0.099926550
[311] -1.016127462  2.707595650 -1.924866225  0.194470936  0.524546343
[316] -0.113350207 -0.731301412 -0.247445456  0.141188050  2.452680685
[321]  3.783418608  3.395677578  2.485046447 -1.684136148 -0.293449827
[326] -2.877603283  0.173403788 -0.010520554 -0.113175772 -0.639489440
[331]  3.822612373 -2.534144510  3.995674762  3.657938412  2.773245255
[336] -0.868036386 -0.641763655  1.576633763  1.201769830  2.603593213
[341]  2.105340687  0.785432978  1.208957624  0.909149115  0.494807691
[346]  0.831743281  1.132180311  0.434184960 -0.239895001 -1.519836140
[351]  2.686140433 -0.848165861  2.986885128 -0.445386675  1.029336696
[356]  0.546114240  0.909568623  0.374910267 -0.567841066  0.995382537
[361] -1.196576753 -2.487057201 -1.227582810  1.884888126  0.075088768
[366]  0.348654887  1.918900993  0.320470388  0.964145854  3.294779113
[371]  2.387672889  0.325134020 -2.243466322 -0.914475142  3.138942075
[376] -0.309562378 -1.497949873 -0.490457802 -2.106821771  0.508264886
[381] -1.539258034 -4.057020142 -2.211092178 -1.420103406 -2.256215182
[386]  1.962499228  0.102893872 -4.430640565 -0.634512732 -1.227301151
[391] -0.563196551 -0.818686889  2.887374634 -2.515508782  1.428260281
[396]  1.796770977  2.740244852 -2.810888621 -1.102811223 -3.490174883
[401]  0.376090246 -0.442968571  0.413511242 -1.173364325 -1.275352437
[406] -4.869338828  1.509526499  1.160544721 -1.546499160 -2.439321046
[411] -1.760336518 -2.384889469 -2.350145336 -2.953240817 -2.147342177
[416]  0.171643390  0.779908424 -0.038281824  0.167353504 -0.030088769
[421]  1.141481808 -2.631311530  0.251557495 -1.020301235  0.647607448
[426] -1.199874516  1.040807601  1.282710295  1.164822620  1.505002715
[431] -1.288908467  1.518149312 -3.100053155 -2.067627071 -3.026497062
[436]  1.051683684  1.728447218  0.124002335  1.866088975 -3.620335585
[441]  0.018989040  1.744266709 -3.270054205 -1.402268992  0.040066193
[446]  0.248110815 -4.869338828 -1.724371715 -2.424141222 -2.135333719
[451] -0.818137898  0.861951027 -1.865656165  1.051772064  2.482974369
[456]  0.470908399 -0.515070523 -0.958593264  0.819934405 -0.642854099
[461] -3.433898103 -3.183987163 -0.181510399 -1.115625444 -0.588990252
[466]  1.358374629 -1.117505943  0.836349358 -1.988733697  0.506718499
[471]  2.794219191 -2.634077590  0.100104735 -2.479936719 -4.406558814
[476]  1.752044853 -4.265596688  0.537729701 -4.079660712 -3.163722241
[481]  0.942713303  2.301165817 -2.118372261  2.015209849 -2.784502771
[486] -2.001775851 -0.950343113 -0.494596446 -1.960369474  1.188529583
[491] -0.283033139 -4.869338828  0.538179112  0.887770489  0.526733204
[496] -1.954902213 -1.050195595 -0.541332611  4.137622905  0.079462352
[501] -3.655599878 -0.956058387 -2.296332994 -0.350440810  3.832363873
[506]  1.192573998 -4.493319023  0.818560147 -4.457448712  1.593275288
[511] -0.121835595 -1.181232221 -0.564223044 -2.072890640 -3.784985884
[516]  0.735659987  1.915686125 -1.070203225 -2.253458059  2.045103408
[521]  0.649473920  1.004118825  2.225982380  1.147623684 -4.457448712
[526] -4.030539009  1.673793803 -0.314828044 -2.837652918 -1.902297114
[531] -0.550320829 -2.320084334 -2.158063553 -3.106405670 -0.432544699
[536] -2.867873074 -2.148285654  4.204882884  3.964972800  3.646809295
[541] -1.707646162 -0.059263053 -0.213931091 -0.900945181  0.572797506
[546]  0.634237059  0.893264285  2.979455689 -1.316334249  1.235670312
[551]  2.740687790  0.686917827 -0.359924693  0.544713459 -0.512547077
[556]  2.196783354  1.722068443  0.357372589  3.450283725  1.693111329
[561]  1.727876312 -0.298845160  0.023723699 -0.920828279  1.528992264
[566]  0.125822927 -0.593735081 -0.052316793 -0.732780740  2.948733050
[571] -1.268997277  1.128902483 -1.463934905  0.704719034 -0.937282960
[576] -0.932214726 -1.464676585  3.081977038 -1.548604625 -2.785725816
[581] -1.573726968  1.489280172  2.600585195  2.747122204 -0.410373582
[586]  2.106886164  3.886725150  2.736183244  0.845877357 -1.682549542
[591] -0.766163235 -0.314311744  0.816040613 -0.523274930 -0.391087138
[596]  3.293958791  1.767269183 -1.234223089  1.705025750  2.870853744
[601] -1.499971169 -1.727938169 -2.044474252  3.960577503  2.696871915
[606]  2.664579858 -0.646739870  2.966500089  0.087995504  0.984969176
[611] -0.317162470  0.659232691  4.293546655 -1.003747688 -0.705280658
[616] -0.686491366  4.196901685 -1.257657950 -0.855224177  2.493673455
[621] -0.066795762 -2.894291821 -3.209213650  1.211865357  0.268179865
[626]  3.059219541  2.462114954  2.762670383  3.188267505  2.139004135
[631] -0.888321910 -0.970696056 -1.450210370  1.159031352  0.504220004
[636] -2.290710270  0.933401226 -0.918938097 -0.869903075  1.722307508
[641]  0.117180275 -1.398181786  2.157463084  2.079948002 -1.398315412
[646] -0.400455924  0.223549398 -0.333512034  1.088312927 -1.484649905
[651] -0.251886379  1.179410347 -0.270321927 -2.374241395 -2.927880920
[656]  0.232394717 -0.610179699 -2.008805417  1.139118713 -0.606484839
[661] -0.671676600 -1.338148516  1.524218481  0.063489069 -0.915404889
[666] -0.897039738 -0.093550205  0.656064664  3.272500377  0.182757300
[671] -1.676047339  1.340684429  1.084237457  0.100452059 -2.276317714
[676] -1.849992274 -0.637685493 -1.419242681 -1.742454851  1.410643892
[681]  0.652951399 -3.589816514  0.953768005 -0.064068078  0.875459276
[686]  0.625473958 -1.355818375  3.669305299 -2.169382217  0.739868699
[691] -1.572268626  2.596967723 -3.104296391  0.790688498  1.106192715
[696] -1.860152920 -1.836972933 -2.725950653  1.152996688 -1.295430227
[701]  1.153536439  0.900256800 -1.579935599  1.348906377 -3.448831214
[706] -2.899388882 -2.802640976 -1.490515092  2.868669072 -0.422382664
[711] -1.672775042 -2.479538893 -2.006522289 -0.922995722 -0.451094648
[716] -2.779386217  2.615505120  4.150513731  3.159393826  2.964458106
[721]  1.357251687  3.487571324  4.063876023  0.506992619  2.917101282
[726]  0.787543486  2.012801034 -0.519401667  0.295342603  0.429894538
[731] -2.034578441  0.808430310  3.519717313  4.102648233  0.414537868
[736]  1.127132690  2.296172324  4.129984018 -0.157699360  0.587691689
[741]  0.341420591  0.135043513 -1.661503158 -2.333215437  3.398757831
[746]  3.292636403  2.957436284 -0.341960040 -0.535498504 -2.116176241
[751]  0.355504221 -0.237386449 -0.179973754 -0.164939318  1.540058853
[756]  2.598956749  0.384389211 -1.428189308  0.421025696 -0.331687790
[761]  1.292637594  1.019058667 -1.767066905 -2.473825726 -1.276784066
[766] -3.438527888 -3.113762921 -2.371984795  0.306365733  0.008139678
[771]  1.095099814 -1.038257444 -1.585692792  0.705103526
attr(,"cluster")
  [1] High High Low  High High Low  High Low  High High Low  High High Low  High
 [16] High Low  High High High High Low  Low  High High High Low  High Low  Low 
 [31] High Low  Low  High Low  High High High High High High High Low  High Low 
 [46] Low  Low  High Low  Low  Low  Low  Low  Low  High Low  High Low  Low  High
 [61] High Low  Low  High High Low  Low  Low  Low  High High Low  High High Low 
 [76] High Low  Low  Low  High Low  High Low  Low  Low  Low  Low  Low  High Low 
 [91] Low  Low  Low  High Low  High Low  Low  High Low  Low  High Low  High Low 
[106] Low  High Low  High Low  Low  High Low  Low  Low  High Low  Low  Low  High
[121] High Low  Low  High Low  High Low  Low  Low  Low  High Low  High High High
[136] Low  High High Low  Low  High High Low  High Low  Low  Low  High High High
[151] High High Low  High Low  Low  Low  High Low  Low  High High High High Low 
[166] Low  Low  Low  High Low  High Low  Low  High High High Low  Low  Low  High
[181] High Low  High High High Low  High Low  Low  Low  Low  Low  Low  Low  Low 
[196] High High High High High High High High High High High Low  High High High
[211] High Low  High Low  Low  Low  Low  Low  Low  Low  Low  Low  Low  High Low 
[226] Low  Low  Low  Low  Low  Low  Low  Low  Low  Low  High High Low  High High
[241] Low  Low  Low  Low  High High High Low  High Low  High Low  High High High
[256] Low  Low  Low  Low  High Low  High High Low  High Low  Low  High High Low 
[271] Low  High Low  Low  Low  Low  Low  Low  Low  High Low  Low  Low  Low  High
[286] High Low  High High High Low  Low  Low  Low  Low  Low  Low  High High High
[301] High High High High High Low  High High Low  Low  Low  High Low  High Low 
[316] High High Low  High High High Low  High Low  Low  Low  Low  High High High
[331] High Low  High High High Low  Low  High High High High High High High High
[346] Low  High High Low  Low  High High High Low  High High Low  High Low  Low 
[361] Low  Low  High Low  High High High Low  High High High Low  Low  Low  High
[376] High Low  Low  Low  High High Low  Low  High Low  High High Low  Low  Low 
[391] Low  High High Low  High High Low  Low  Low  Low  High High Low  Low  Low 
[406] Low  High Low  Low  Low  Low  Low  Low  Low  High High High Low  Low  Low 
[421] Low  Low  High Low  Low  Low  High High Low  High Low  High Low  Low  Low 
[436] High High High Low  Low  Low  High Low  Low  High High Low  Low  Low  Low 
[451] Low  High Low  High High High High Low  Low  High Low  Low  Low  Low  High
[466] Low  High Low  High High Low  Low  Low  Low  Low  High Low  High Low  Low 
[481] Low  High Low  High Low  Low  Low  High Low  High Low  Low  Low  High High
[496] Low  Low  Low  High Low  Low  Low  Low  Low  High High Low  High Low  High
[511] High High High Low  Low  High High Low  High High High High High High Low 
[526] Low  High Low  Low  Low  High High Low  High High Low  Low  High High High
[541] Low  Low  High Low  High Low  High High Low  High High High High High Low 
[556] High High Low  High High High Low  High Low  High Low  High High Low  High
[571] Low  High High High Low  Low  Low  High Low  High Low  High High High High
[586] High High High High Low  Low  High High Low  Low  High Low  High High High
[601] Low  Low  Low  High High High High High Low  High Low  High High Low  Low 
[616] Low  High Low  Low  High Low  High Low  High High High High High High High
[631] Low  High Low  High High High Low  Low  Low  High High Low  High High Low 
[646] Low  Low  Low  Low  Low  High High High Low  Low  Low  High Low  High High
[661] High Low  High High High Low  High High High High High Low  High Low  Low 
[676] High Low  Low  Low  Low  High Low  Low  High Low  Low  Low  High Low  Low 
[691] Low  High Low  High Low  Low  High Low  High High High High Low  Low  Low 
[706] Low  Low  Low  High Low  Low  Low  High High Low  Low  High High Low  High
[721] High High High High High High High Low  Low  High Low  Low  High High High
[736] High High High Low  Low  High High Low  Low  High High High High Low  Low 
[751] High High High High High High High Low  High Low  High High Low  High Low 
[766] Low  Low  Low  Low  Low  High Low  Low  High
Levels: Low High
attr(,"gstari")
[1] FALSE
attr(,"call")
localG(x = nga_wp26391$`pct nonfunctional`, listw = knn_lw)
attr(,"class")
[1] "localG"</code></pre>
</div>
</div>
<p>The output of localG() function is a vector of G or Gstar values, with attributes “gstari” set to TRUE or FALSE, “call” set to the function call, and “class” as “local G”.</p>
<p>The Gi Statistics is represented as z-score. Greater values mean greater intensity of clustering while the direction (positive or negative) indicates high or low clusters.</p>
<p>Next, we will join the Gi values to their corresponding nga_wp26391 sf data frame by using the below code chunks:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>nga.gi<span class="ot">&lt;-</span><span class="fu">cbind</span>(nga_wp26391,<span class="fu">as.matrix</span>(gi.adaptive))<span class="sc">%&gt;%</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">gstat_adaptive=</span>as.matrix.gi.adaptive.)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Do take note that there are 3 operations performed with the above code chunks:</p>
<ul>
<li><p>as.matrix() convert the output vector (from the previous code chunk) gi.adaptive into an R matrix object.</p></li>
<li><p>cbind() then join the nga_wp26391 sf dataframe with the newly created gi.adaptive matrix to produce a new SpatialPolygon Data frame called nga.gi</p></li>
<li><p>rename() renames the gi.adaptive field name to gstat_adaptive.</p></li>
</ul>
</section>
<section id="mapping-gi-values-with-adaptive-distance-weights" class="level3">
<h3 class="anchored" data-anchor-id="mapping-gi-values-with-adaptive-distance-weights">Mapping Gi values with adaptive distance weights</h3>
<p>The code chunk below shows the function used to map the Gi values derived using the adaptive distance weight matrix.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>wpt_nonfunctional<span class="ot">&lt;-</span><span class="fu">qtm</span>(nga_wp26391,<span class="st">"pct nonfunctional"</span>)</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>Gimap<span class="ot">&lt;-</span><span class="fu">tm_shape</span>(nga.gi)<span class="sc">+</span></span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col=</span><span class="st">"gstat_adaptive"</span>,</span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">style=</span><span class="st">"pretty"</span>,</span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette=</span><span class="st">"-RdBu"</span>,</span>
<span id="cb85-6"><a href="#cb85-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">title=</span><span class="st">"local Gi"</span>)<span class="sc">+</span></span>
<span id="cb85-7"><a href="#cb85-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha=</span><span class="fl">0.5</span>)</span>
<span id="cb85-8"><a href="#cb85-8" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(wpt_nonfunctional,Gimap,<span class="at">asp=</span><span class="dv">1</span>,<span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex1_files/figure-html/unnamed-chunk-62-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the above maps, we notice that cold spots were located in the North East region of Nigeria while the hot spots were located in the South West region of Nigeria. However, in the case of Nigeria, cold spots may not be relevant as some regions have no water points at all. Instead, it is more important to focus more on the spatial distribution of non-functional water points and their corresponding proportion to the total number of water points.</p>
</section>
</section>
<section id="limitations" class="level2">
<h2 class="anchored" data-anchor-id="limitations">Limitations</h2>
<p>Some of the regions did not have water points or missing data. Therefore, as mentioned above, the non-functional water points rates were adjusted to become 0. This does not necessarily mean that the local governments governments are adept at maintaining the water points. As a result, it is important not to jump to any conclusion on those “cold spots” area.</p>
<p>Due to the requirements of the exercise, we have not tried to find out the factors (such as population size) which can affect the distribution of the functional or non-functional water point rates.</p>
</section>
<section id="reference" class="level2">
<h2 class="anchored" data-anchor-id="reference">Reference</h2>
<p>Runfola, D. et al.&nbsp;(2020) geoBoundaries: A global database of political administrative boundaries. PLoS ONE 15(4): e0231866. https://doi.org/10.1371/journal.pone.0231866</p>
<p><em>Access data</em>. WPdx. (n.d.). Retrieved November 30, 2022, from https://www.waterpointdata.org/access-data/</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>